### ISSUE TITLE
希望支持多个requirments文件

### ISSUE THREAD

**Issue by herbieliang** [ferstar/check-requirements-txt#1]
目前貌似只支持单个的requirments.txt文件，但我一般是建立requirments文件夹，里面根据环境建立不同环境需要的包依赖，这样貌似检测不出来

**Comment by ferstar** [comment]
其实是支持多个 requirements.txt 的, 但是可能跟你期望的不是很相符

https://github.com/ferstar/check-requirements-txt/blob/master/check_requirements_txt.py#L119

这里我会匹配当前目录下所有`*requirements*.txt`这种 pattern 的文件

欢迎 PR

**Comment by ferstar** [comment]
@herbieliang 可以自定义`requirements.txt`路径了，支持多个requirements文件
